apiVersion: v1
kind: Service
metadata:
  name: aspcore3-service
  labels:
   app: aspcore3-service
spec:
  selector:
    app: aspcore3
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
