trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool: Default
      #vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@0
      displayName: Build an image
      inputs:
        azureSubscription: 'Internal (1ba0c403-6df1-461d-a7bc-c5471edbd702)'
        azureContainerRegistry: '{"loginServer":"pieterd.azurecr.io", "id" : "/subscriptions/1ba0c403-6df1-461d-a7bc-c5471edbd702/resourceGroups/devopsrg/providers/Microsoft.ContainerRegistry/registries/pieterd"}'
        dockerFile: '**/Dockerfile'
        includeLatestTag: true
    - task: Docker@0
      displayName: 'Push an image'
      inputs:
        azureSubscription: 'Internal (1ba0c403-6df1-461d-a7bc-c5471edbd702)'
        azureContainerRegistry: '{"loginServer":"pieterd.azurecr.io", "id" : "/subscriptions/1ba0c403-6df1-461d-a7bc-c5471edbd702/resourceGroups/devopsrg/providers/Microsoft.ContainerRegistry/registries/pieterd"}'
        action: 'Push an image'
        includeLatestTag: true
    - task: Kubernetes@1
      displayName: 'kubectl set'
      inputs:
        kubernetesServiceEndpoint: 201907asp3
        namespace: aspcore3
        command: set
        arguments: 'image deployment/aspcore3-deployment aspcore3-container=pieterd.azurecr.io/$(Build.Repository.Name):$(Build.BuildId)'
#    - task: Kubernetes@1
#      displayName: 'kubectl apply -f **/yml/deployment.yml'
#      inputs:
#        connectionType: 'Azure Resource Manager'
#        azureSubscriptionEndpoint: 'Internal (1ba0c403-6df1-461d-a7bc-c5471edbd702)'
#        azureResourceGroup: aksrg201907
#        kubernetesCluster: aks201907
#        namespace: aspcore3
#        command: apply
#        arguments: '-f ./yml/deployment.yml'
